### PR TITLE
Jesse

### PR DESCRIPTION
**Pull request by jesseAaltonen**
add comment

### CODE REVIEW

**Review by EetuSaarinen — CHANGES_REQUESTED** [review]
maybe typo right?

**Review by SauliKaloinen — CHANGES_REQUESTED** [review]
You had some typos in line 10 comment. Fix them and request another merge.

**Review by SauliKaloinen — APPROVED** [review]
Now it looks fine. Approved.

**Review by EetuSaarinen — APPROVED** [review]
Now it looks very good, great work jesse!

**Pull request merged**
